general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = /home/dasgaca/shell-wallpapers/images/calming-nature-wallpaper-free-image.jpeg
    blur_passes = 3
    blur_size = 8
    brightness = 0.6
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.2
    inner_color = rgba(20, 20, 20, 0.80)
    font_color = rgb(205, 214, 244)
    fade_on_empty = true
    placeholder_text = <i>Şifre...</i>
    hide_input = false
    rounding = 10
    check_color = rgb(137, 180, 250)
    fail_color = rgb(243, 139, 168)
    fail_text = <i>Hatalı şifre</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(205, 214, 244, 0.90)
    font_size = 72
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(205, 214, 244, 0.60)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 120
    halign = center
    valign = center
}
