[General]
ScreenWidth="2560"
ScreenHeight="1440"
ScreenPadding=""

Font="pixelon"
FontSize="12"

KeyboardSize="0.4"

RoundCorners="20"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder="Backgrounds/custom.jpeg"
Background="Backgrounds/custom.jpeg"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.2"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#cdd6f4"
DateTextColor="#cdd6f4"
TimeTextColor="#cdd6f4"

FormBackgroundColor="#1e1e2e"
BackgroundColor="#1e1e2e"
DimBackgroundColor="#1e1e2e"

LoginFieldBackgroundColor="#313244"
PasswordFieldBackgroundColor="#313244"
LoginFieldTextColor="#cdd6f4"
PasswordFieldTextColor="#cdd6f4"
UserIconColor="#cdd6f4"
PasswordIconColor="#cdd6f4"

PlaceholderTextColor="#6c7086"
WarningColor="#f38ba8"

LoginButtonTextColor="#1e1e2e"
LoginButtonBackgroundColor="#89b4fa"
SystemButtonsIconsColor="#cdd6f4"
SessionButtonTextColor="#cdd6f4"
VirtualKeyboardButtonTextColor="#cdd6f4"

DropdownTextColor="#1e1e2e"
DropdownSelectedBackgroundColor="#89b4fa"
DropdownBackgroundColor="#313244"

HighlightTextColor="#1e1e2e"
HighlightBackgroundColor="#89b4fa"
HighlightBorderColor="transparent"

HoverUserIconColor="#ffffff"
HoverPasswordIconColor="#ffffff"
HoverSystemButtonsIconsColor="#ffffff"
HoverSessionButtonTextColor="#ffffff"
HoverVirtualKeyboardButtonTextColor="#ffffff"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="8"
Blur="2.0"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="left"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="true"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
